// scriberr-frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { isAuthenticated } from '$lib/stores';
	import { LoaderCircle } from 'lucide-svelte';
	import { toast } from 'svelte-sonner';

	// --- STATE ---
	let username = $state('');
	let password = $state('');
	let isLoading = $state(false);

	// --- LOGIC ---
	async function handleLogin() {
		if (!username || !password) {
			toast.error('Please enter both username and password.');
			return;
		}

		isLoading = true;

		try {
			const response = await fetch('/api/auth/login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ username, password }),
				credentials: 'include'
			});

			const result = await response.json();

			if (!response.ok) {
				throw new Error(result.error || 'Login failed. Please check your credentials.');
			}

			toast.success('Login successful!');
			isAuthenticated.set(true);
			await goto('/app', { replaceState: true });
		} catch (error) {
			const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred.';
			toast.error('Login Failed', { description: errorMessage });
			password = ''; // Clear password field on failure
		} finally {
			isLoading = false;
		}
	}

	function handleKeyPress(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			handleLogin();
		}
	}
</script>

<div class="flex min-h-screen items-center justify-center bg-gray-900 p-4">
	<div class="w-full max-w-sm rounded-xl border border-gray-700 bg-gray-800 p-8 shadow-lg">
		<div class="mb-8 text-center">
			<h1 class="text-3xl font-bold text-gray-100">Scriberr</h1>
			<p class="text-gray-400">Sign in to your account</p>
		</div>

		<form class="space-y-6" on:submit|preventDefault={handleLogin} on:keypress={handleKeyPress}>
			<div class="space-y-2">
				<label for="username" class="text-sm font-medium text-gray-300">Username</label>
				<Input
					id="username"
					type="text"
					placeholder="admin"
					bind:value={username}
					disabled={isLoading}
					class="border-gray-600 bg-gray-700 text-gray-200 focus:border-blue-500 focus:ring-blue-500"
					required
				/>
			</div>

			<div class="space-y-2">
				<label for="password" class="text-sm font-medium text-gray-300">Password</label>
				<Input
					id="password"
					type="password"
					placeholder="••••••••"
					bind:value={password}
					disabled={isLoading}
					class="border-gray-600 bg-gray-700 text-gray-200 focus:border-blue-500 focus:ring-blue-500"
					required
				/>
			</div>

			<div>
				<Button
					type="submit"
					class="w-full bg-blue-600 text-white hover:bg-blue-700"
					disabled={isLoading}
				>
					{#if isLoading}
						<LoaderCircle class="mr-2 h-4 w-4 animate-spin" />
						<span>Signing in...</span>
					{:else}
						<span>Sign In</span>
					{/if}
				</Button>
			</div>
		</form>
		<div class="mt-4 text-center">
			<p class="text-xs text-gray-500">Default credentials: admin / password</p>
		</div>
	</div>
</div>

// web/frontend/src/features/auth/components/Login.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScriberrLogo } from "@/components/ScriberrLogo";
import { useNavigate } from "react-router-dom";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

interface LoginProps {
	onLogin: (token: string) => void;
}

export function Login({ onLogin }: LoginProps) {
	const navigate = useNavigate();
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState("");

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		setError("");
		setLoading(true);

		try {
			const response = await fetch("/api/v1/auth/login", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					username,
					password,
				}),
			});

			if (response.ok) {
				const data = await response.json();
				onLogin(data.token);
			} else {
				const error = await response.json();
				setError(error.error || "Login failed");
			}
		} catch (error) {
			console.error("Login error:", error);
			setError("Network error. Please try again.");
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="min-h-screen bg-carbon-50 dark:bg-carbon-900 flex items-center justify-center">
			<div className="absolute top-8 right-8">
				<ThemeSwitcher />
			</div>

			<div className="w-full max-w-md space-y-8">
				<div className="text-center">
					<div className="flex justify-center mb-6">
						<ScriberrLogo onClick={() => navigate('/')} />
					</div>
					<h2 className="text-3xl font-bold text-carbon-900 dark:text-carbon-100">
						Sign in to Scriberr
					</h2>
					<p className="mt-2 text-carbon-600 dark:text-carbon-400">
						Access your audio transcription workspace
					</p>
				</div>

				<Card className="bg-white dark:bg-carbon-800 border-carbon-200 dark:border-carbon-700">
					<CardHeader>
						<CardTitle className="text-carbon-900 dark:text-carbon-100">Login</CardTitle>
						<CardDescription className="text-carbon-600 dark:text-carbon-400">
							Enter your credentials to continue
						</CardDescription>
					</CardHeader>
					<CardContent>
						<form onSubmit={handleSubmit} className="space-y-4">
							{error && (
								<div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3">
									<p className="text-red-700 dark:text-red-300 text-sm">{error}</p>
								</div>
							)}

							<div className="space-y-2">
								<Label htmlFor="username" className="text-carbon-700 dark:text-carbon-300">
									Username
								</Label>
								<Input
									id="username"
									type="text"
									placeholder="Enter your username"
									value={username}
									onChange={(e) => setUsername(e.target.value)}
									disabled={loading}
									required
									className="bg-white dark:bg-carbon-800 border-carbon-300 dark:border-carbon-600 text-carbon-900 dark:text-carbon-100"
								/>
							</div>

							<div className="space-y-2">
								<Label htmlFor="password" className="text-carbon-700 dark:text-carbon-300">
									Password
								</Label>
								<Input
									id="password"
									type="password"
									placeholder="Enter your password"
									value={password}
									onChange={(e) => setPassword(e.target.value)}
									disabled={loading}
									required
									className="bg-white dark:bg-carbon-800 border-carbon-300 dark:border-carbon-600 text-carbon-900 dark:text-carbon-100"
								/>
							</div>

							<Button
								type="submit"
								className="w-full bg-blue-600 hover:bg-blue-700 text-white"
								disabled={loading || !username.trim() || !password.trim()}
							>
								{loading ? "Signing in..." : "Sign In"}
							</Button>
						</form>
					</CardContent>
				</Card>

				<div className="text-center">
					<p className="text-sm text-carbon-600 dark:text-carbon-400">
						Secure authentication required for API key management
					</p>
				</div>
			</div>
		</div>
	);
}
