// web/frontend/src/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        // Base styles
        "flex h-9 w-full min-w-0 rounded-[var(--radius-btn)] border bg-[var(--bg-main)] px-3 py-1 text-base shadow-xs transition-all outline-none md:text-sm",
        // Border
        "border-[var(--border-subtle)]",
        // Text and placeholder
        "text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)]",
        // Selection
        "selection:bg-[var(--brand-solid)]/20 selection:text-[var(--text-primary)]",
        // Focus state - brand color
        "focus-visible:border-[var(--brand-solid)] focus-visible:ring-[3px] focus-visible:ring-[var(--brand-solid)]/20",
        // File input styles
        "file:text-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium",
        // Disabled
        "disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50",
        // Invalid state
        "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
        // Dark mode adjustments
        "dark:bg-[var(--bg-card)]",
        className
      )}
      {...props}
    />
  )
}

export { Input }

// src/lib/components/ui/input/input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements";
	import type { WithElementRef } from "bits-ui";
	import { cn } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		...restProps
	}: WithElementRef<HTMLInputAttributes> = $props();
</script>

<input
	bind:this={ref}
	class={cn(
		"border-input placeholder:text-muted-foreground focus-visible:ring-ring flex h-9 w-full rounded-md border bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50",
		className
	)}
	bind:value
	{...restProps}
/>
