// web/frontend/src/pages/Login.tsx
import { useState } from "react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { ScriberrLogo } from "../components/ScriberrLogo";
import { ThemeSwitcher } from "../components/ThemeSwitcher";

interface LoginProps {
	onLogin: (token: string) => void;
}

export function Login({ onLogin }: LoginProps) {
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState("");

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		setError("");
		setLoading(true);

		try {
			const response = await fetch("/api/v1/auth/login", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					username,
					password,
				}),
			});

			if (response.ok) {
				const data = await response.json();
				onLogin(data.token);
			} else {
				const error = await response.json();
				setError(error.error || "Login failed");
			}
		} catch (error) {
			console.error("Login error:", error);
			setError("Network error. Please try again.");
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
			<div className="absolute top-8 right-8">
				<ThemeSwitcher />
			</div>
			
			<div className="w-full max-w-md space-y-8">
				<div className="text-center">
					<div className="flex justify-center mb-6">
						<ScriberrLogo />
					</div>
					<h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
						Sign in to Scriberr
					</h2>
					<p className="mt-2 text-gray-600 dark:text-gray-400">
						Access your audio transcription workspace
					</p>
				</div>

				<Card className="bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700">
					<CardHeader>
						<CardTitle className="text-gray-900 dark:text-gray-100">Login</CardTitle>
						<CardDescription className="text-gray-600 dark:text-gray-400">
							Enter your credentials to continue
						</CardDescription>
					</CardHeader>
					<CardContent>
						<form onSubmit={handleSubmit} className="space-y-4">
							{error && (
								<div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3">
									<p className="text-red-700 dark:text-red-300 text-sm">{error}</p>
								</div>
							)}
							
							<div className="space-y-2">
								<Label htmlFor="username" className="text-gray-700 dark:text-gray-300">
									Username
								</Label>
								<Input
									id="username"
									type="text"
									placeholder="Enter your username"
									value={username}
									onChange={(e) => setUsername(e.target.value)}
									disabled={loading}
									required
									className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100"
								/>
							</div>
							
							<div className="space-y-2">
								<Label htmlFor="password" className="text-gray-700 dark:text-gray-300">
									Password
								</Label>
								<Input
									id="password"
									type="password"
									placeholder="Enter your password"
									value={password}
									onChange={(e) => setPassword(e.target.value)}
									disabled={loading}
									required
									className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100"
								/>
							</div>
							
							<Button
								type="submit"
								className="w-full bg-blue-600 hover:bg-blue-700 text-white"
								disabled={loading || !username.trim() || !password.trim()}
							>
								{loading ? "Signing in..." : "Sign In"}
							</Button>
						</form>
					</CardContent>
				</Card>

				<div className="text-center">
					<p className="text-sm text-gray-600 dark:text-gray-400">
						Secure authentication required for API key management
					</p>
				</div>
			</div>
		</div>
	);
}

// src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle
	} from '$lib/components/ui/card';
	import { Label } from '$lib/components/ui/label';
	import { Input } from '$lib/components/ui/input';
	import { Button } from '$lib/components/ui/button';
	import { Alert, AlertDescription } from '$lib/components/ui/alert';

	let error = '';

	function handleSubmit(event: SubmitEvent) {
		return async ({ result }) => {
			if (result.type === 'success') {
				// Store the token in localStorage
				if (result.data?.token) {
					localStorage.setItem('sessionToken', result.data.token);
					if (result.data.expiresAt) {
						localStorage.setItem('sessionExpires', result.data.expiresAt);
					}
				}
				goto('/');
			} else {
				error = 'Invalid credentials';
			}
		};
	}
</script>

<div class="flex min-h-screen items-center justify-center bg-gray-50 p-4">
	<Card class="w-full max-w-md">
		<CardHeader>
			<CardTitle>Admin Login</CardTitle>
			<CardDescription>Enter your credentials to access the dashboard</CardDescription>
		</CardHeader>
		<CardContent>
			{#if error}
				<Alert variant="destructive" class="mb-4">
					<AlertDescription>{error}</AlertDescription>
				</Alert>
			{/if}
			<form method="POST" use:enhance={handleSubmit} class="space-y-4">
				<div class="space-y-2">
					<Label for="username">Username</Label>
					<Input type="text" id="username" name="username" required />
				</div>
				<div class="space-y-2">
					<Label for="password">Password</Label>
					<Input type="password" id="password" name="password" required />
				</div>
				<Button type="submit" class="w-full">Sign in</Button>
			</form>
		</CardContent>
	</Card>
</div>
